## Prérequis : Logique du premier ordre (FOL)

Avant de parler de *grounding*, il est nécessaire de rappeler les bases de la logique du premier ordre classique, sur laquelle repose tout le vocabulaire utilisé dans les tutoriels LTN.

### 1. Qu'est-ce que la logique du premier ordre ?

La logique du premier ordre est un langage formel, un ensemble de règles d'écriture strictes qui permet de décrire le monde avec des phrases précises, sans ambiguïté et vérifiables.

**Exemples :**
- "Socrate est un homme"
- "Tous les hommes sont mortels."

C'est le langage standard utilisé en mathématiques et en IA symbolique.

### 2. Le domaine (ou univers du discours)

Le domaine, c'est l'ensemble de tous les objets dont on parle dans notre système logique.

Exemple : si je construis un système logique pour parler d'un petit groupe de personnes, mon domaine $D$ pourrait être :

$$D = \{\text{Léonel}, \text{Mélène}, \text{Alice}, \text{Abdel}\}$$

Le domaine ne contient que des objets qui existent "dans notre univers logique". Il délimite le terrain de jeu de toute la logique.

### 3. Les constantes

Une constante est un nom propre, un symbole qui désigne toujours le même objet précis du domaine.

Dans notre domaine $D$, le symbole `abdel` est une constante qui pointe vers Abdel, et rien d'autre.

### 4. Les variables

Une variable est un espace réservé, un symbole générique (souvent noté $x, y, z$) qui peut désigner n'importe quel élément du domaine.

### 5. Les prédicats

Un prédicat est une propriété ou une relation qu'on peut attribuer à un ou plusieurs objets, et qui est soit vraie, soit fausse.

**Exemple à un argument (prédicat unaire, "1-aire") :**

$$\text{EstÉtudiant}(x)$$

Ce prédicat prend un seul objet en entrée et dit si cet objet a la propriété "être étudiant". Par exemple :
- $\text{EstÉtudiant}(\text{Abdel}) = \text{Vrai}$
- $\text{EstÉtudiant}(\text{Mélène}) = \text{Faux}$

**Exemple à deux arguments (prédicat binaire, "2-aire") :**

$$\text{EstAmoureuxDe}(x, y)$$

Ce prédicat prend deux objets en entrée et exprime une relation entre eux :
- $\text{EstAmoureuxDe}(\text{Alice}, \text{Abdel}) = \text{Vrai}$
- $\text{EstAmoureuxDe}(\text{Abdel}, \text{Alice})$ pourrait avoir une valeur différente si la relation n'est pas symétrique.

L'**arité** d'un prédicat désigne le nombre d'arguments qu'il prend. Un prédicat à $n$ arguments est dit **$n$-aire**.

### 6. Le domaine d'un prédicat $n$-aire

Quand un prédicat prend $n$ arguments, chaque argument vient du domaine $D$. On dit alors que le prédicat est défini sur $D^n$ , c'est-à-dire l'ensemble de tous les $n$-uplets possibles d'objets du domaine.

### 7. Les fonctions

Contrairement à un prédicat, une fonction en logique prend des objets du domaine et renvoie un autre objet du domaine.

Exemple : $\text{PèreDe}(x)$ est une fonction qui, appliquée à une personne, renvoie une autre personne, son père. Avec notre domaine : $\text{PèreDe}(\text{Alice}) = \text{Léonel}$. La sortie reste dans le domaine.

### 8. Les connecteurs logiques

| Symbole | Nom | Description | Exemple |
|---|---|---|---|
| $\lnot$ | Négation | Inverse la valeur de vérité | $\lnot\text{EstÉtudiant}(\text{Abdel}) = \text{Faux}$ (car Abdel est étudiant) |
| $\land$ | Conjonction ("ET") | Vraie uniquement si les deux propositions sont vraies simultanément | $\text{EstÉtudiant}(\text{Abdel}) \land \text{EstAmoureuxDe}(\text{Alice},\text{Abdel}) = \text{Vrai}$ |
| $\lor$ | Disjonction ("OU") | Vraie si au moins une des deux propositions est vraie, fausse uniquement si les deux sont fausses | $\text{EstÉtudiant}(\text{Abdel}) \lor \text{EstAmoureuxDe}(\text{Abdel},\text{Alice}) = \text{Vrai}$ |
| $\implies$ | Implication | $P \implies Q$ exprime que si $P$ est vraie, alors $Q$ est nécessairement vraie. Équivaut à $\lnot P \lor Q$ ("non $P$ ou $Q$") | $\text{EstHumain}(x) \implies \text{EstMortel}(x)$ |

### 9. Les quantificateurs

Ils permettent de parler de plusieurs objets du domaine sans les nommer un par un :

- $\forall  x\, \phi(x)$ : "pour tout $x$ du domaine, $\phi(x)$ est vrai". Exemple : $\forall  x\, \text{EstMortel}(x)$ = "tout le monde est mortel".
- $\exists  x\, \phi(x)$ : "il existe (au moins) un $x$ du domaine pour lequel $\phi(x)$ est vraie". Exemple : $\exists x\, \text{EstÉtudiant}(x)$ = "il y a au moins un étudiant".

### 10. Une formule

Une formule $\phi$ est simplement une phrase logique bien construite, combinant tout ce qu'on vient de voir : des prédicats, appliqués à des constantes ou variables, combinés par des connecteurs, éventuellement quantifiés.

**Exemple :**

$$\forall x\, (\text{EstÉtudiant}(x) \implies \exists y\, \text{EstAmiDe}(x,y))$$

Traduction : "Pour tout $x$, si $x$ est étudiant, alors il existe un $y$ tel que $x$ est ami avec $y$" , autrement dit "tout étudiant a au moins un ami".

### 11. L'interprétation $\mathcal{I}$

L'interprétation $\mathcal{I}$ est la fonction qui fait le pont entre la syntaxe et la sémantique. Elle prend chaque symbole brut du langage et lui assigne un objet concret, dans un domaine choisi au préalable.

Techniquement, $\mathcal{I}$ n'est pas une règle unique , c'est un ensemble de trois assignations, une par type de symbole :

**a) Pour chaque constante → un élément du domaine**

$$\mathcal{I}(c_1) = \text{un élément précis de } D$$

Exemple : si $D = \{\text{Alice}, \text{Bob}, \text{Chloé}\}$, on peut décider $\mathcal{I}(c_1) = \text{Alice}$. Le symbole $c_1$, qui n'était qu'une étiquette vide, "pointe" désormais vers Alice et seulement Alice.

**b) Pour chaque prédicat $n$-aire → un sous-ensemble de $D^n$**

$$\mathcal{I}(P_1) \subseteq D^n$$

Pourquoi un sous-ensemble, et pas directement "vrai ou faux" ? Parce qu'un prédicat doit pouvoir être évalué pour chaque combinaison d'objets possible. La façon la plus propre de dire "ce prédicat est vrai pour telles combinaisons et faux pour toutes les autres" est de lister exactement l'ensemble des combinaisons pour lesquelles il est vrai.

Exemple avec $\text{EstÉtudiant}(x)$ (prédicat unaire, $n=1$) et $D = \{\text{Alice}, \text{Bob}, \text{Chloé}\}$ :

$$\mathcal{I}(\text{EstÉtudiant}) = \{\text{Alice}, \text{Chloé}\}$$

Cela signifie : "le prédicat EstÉtudiant est vrai exactement pour Alice et pour Chloé, et faux pour Bob (et pour tout autre élément du domaine absent de cet ensemble)". Évaluer $\text{EstÉtudiant}(\text{Bob})$ devient alors trivial : Bob appartient-il à $\{\text{Alice}, \text{Chloé}\}$ ? Non , donc c'est faux.

Pour un prédicat binaire comme $\text{EstAmiDe}(x,y)$ ($n=2$), l'interprétation est un ensemble de paires :

$$\mathcal{I}(\text{EstAmiDe}) = \{(\text{Alice},\text{Bob}), (\text{Bob},\text{Alice}), (\text{Chloé},\text{Alice})\}$$

**c) Pour chaque symbole de fonction → une vraie fonction mathématique sur $D$**

$$\mathcal{I}(f_1) : D^n \to D$$

Exemple : $\mathcal{I}(\text{PèreDe})$ associe à chaque personne du domaine une autre personne du domaine (son père).

#### Comment $\mathcal{I}$ permet d'évaluer une formule entière

Une fois ces trois assignations fixées, on évalue une formule en remontant symbole par symbole. Pour $\text{EstÉtudiant}(c_1)$ :

1. $\mathcal{I}(c_1) \to$ Alice.
2. $\mathcal{I}(\text{EstÉtudiant}) \to \{\text{Alice}, \text{Chloé}\}$.
3. Alice appartient-elle à $\{\text{Alice}, \text{Chloé}\}$ ? Oui.
4. Donc $\text{EstÉtudiant}(c_1)$ est **Vrai** sous $\mathcal{I}$.

Les connecteurs et quantificateurs se combinent ensuite avec ces valeurs de vérité de base, selon les règles classiques, pour évaluer des formules entières.

#### Le point crucial : une interprétation n'est qu'un choix parmi d'autres

Rien n'oblige à choisir $\mathcal{I}(c_1) = \text{Alice}$. On aurait pu choisir un domaine complètement différent ($D = \{1,2,3,\dots\}$) et interpréter $c_1$ comme le nombre 5, et $P_1$ comme "être un nombre pair". La *même* formule syntaxique $P_1(c_1)$ deviendrait alors une affirmation totalement différente ("5 est pair" — faux), sans que la syntaxe ait changé.

**C'est précisément ce point qui explique pourquoi LTN introduit un nouveau terme, le *grounding*.** que nous allons découvrir dans les lignes à suivre.

# Grounding en Logic Tensor Networks (LTN)

## Real Logic

### Le problème que Real Logic résout

En logique du premier ordre (FOL) classique, l'interprétation $\mathcal{I}$ cible un domaine $D$ abstrait, un simple ensemble d'objets, sans structure numérique et évalue chaque formule strictement à Vrai ou Faux.

Real Logic, la sémantique utilisée par LTN, s'écarte de ce cadre : le domaine n'est plus abstrait, il est interprété concrètement par des **tenseurs réels**. Puisque LTN interprète des symboles ancrés sur des caractéristiques numériques réelles, on parle de ***grounding***, noté $\mathcal{G}$, plutôt que d'interprétation ; ce nouveau terme marque justement que $\mathcal{G}$ n'est pas une interprétation quelconque, mais une interprétation *contrainte* à toujours cibler l'espace des tenseurs.

Concrètement, $\mathcal{G}$ agit sur deux catégories syntaxiques distinctes :
- à tout **terme** du langage (une constante, une variable, le résultat d'une fonction), $\mathcal{G}$ associe un **tenseur de réels** ;
- à toute **formule** $\phi$, $\mathcal{G}$ associe **un réel dans l'intervalle $[0,1]$** ; un degré de vérité continu, et non plus un booléen strict.

Par simplicité, dans la suite des tutoriels, "tenseur" désignera toujours "tenseur dans le corps des réels".

### La structure du langage : signature + partie logique universelle

Le langage de Real Logic se compose de deux parties :
- une **partie non-logique**, appelée la **signature** : c'est le vocabulaire propre au problème qu'on modélise (les constantes, fonctions et prédicats qu'on choisit) ;
- une **partie logique universelle** : les connecteurs et quantificateurs, communs à toute logique, indépendamment du problème traité.

**La signature comprend :**

- **les constantes** : elles dénotent des individus appartenant à un espace de tenseurs $\bigcup\limits_{n_1 \dots n_d \in \mathbb{N}^*} \mathbb{R}^{n_1 \times \dots \times n_d}$ ; l'union de tous les tenseurs possibles, quel que soit leur rang. Les individus peuvent être prédéfinis (une donnée fixe) ou apprenables (un embedding, ajusté par backpropagation).

- **les variables** : elles dénotent des séquences d'individus ; en pratique, un batch de plusieurs tenseurs.

- **les fonctions** : ce sont des fonctions mathématiques quelconques, prédéfinies ou apprenables ; des fonctions de distance, des régresseurs, etc. Elles peuvent être construites avec n'importe quelle opération PyTorch : fonctions linéaires, réseaux de neurones profonds, et ainsi de suite.

- **les prédicats** : ce sont des fonctions mathématiques qui associent à un domaine $n$-aire d'individus un réel dans $[0,1]$, interprétable comme un degré de vérité. Des exemples de prédicats incluent des mesures de similarité, des classifieurs, etc.

**La partie logique universelle comprend :**

- **les connecteurs** ($\lnot, \land, \lor, \implies$) : modélisés par des opérateurs de connecteurs flous.
- **les quantificateurs** : définis par des agrégateurs flous.

En résumé, LTN reprend l'architecture complète de la logique du premier ordre( signature, connecteurs, quantificateurs) mais remplace systématiquement chaque cible d'interprétation par son équivalent numérique et continu : des tenseurs à la place d'objets abstraits, $[0,1]$ à la place de $\{0,1\}$, des opérateurs flous différentiables à la place des tables de vérité et de l'appartenance ensembliste stricte. C'est ce remplacement qui rend les connaissances logiques exploitables comme contraintes différentiables, entraînables par descente de gradient.

Ce tutoriel explique comment grounder des constantes, des variables, des fonctions et des prédicats.

Pour utiliser LTN correctement, il faut d'abord importer le framework ainsi que PyTorch.

In [1]:
import ltn
import torch
import numpy as np

## Constantes

Les constantes LTN sont groundées sur des tenseurs réels. Chaque constante $c$ est associée à un point $\mathcal{G}(c) \in \bigcup\limits_{n_1 \dots n_d \in \mathbb{N}^*} \mathbb{R}^{n_1 \times \dots \times n_d}$ , c'est-à-dire l'union de tous les espaces de tenseurs possibles, quel que soit leur rang.

**Le rang d'un tenseur** correspond simplement au nombre d'indices nécessaires pour repérer une case à l'intérieur :
- rang $0$ = scalaire (un seul nombre, aucun indice) ;
- rang $1$ = vecteur (un seul indice) ;
- rang $2$ = matrice (deux indices : ligne et colonne) ;
- et ainsi de suite pour les rangs supérieurs.

Rien n'oblige les constantes d'un même système LTN à avoir la même forme de tenseur ; chaque constante vit dans l'espace qui lui correspond. C'est précisément le rôle de l'union $\bigcup_{n_1 \dots n_d}$ : accepter des individus de n'importe quelle forme.

Ici, on définit $\mathcal{G}(c_1) = (2.1, 3)$ , un vecteur de rang 1  et 

$\mathcal{G}(c_2) = \begin{pmatrix} 4.2 & 3 & 2.5 \\ 4 & -1.3 & 1.8 \end{pmatrix}$ 
une matrice de rang 2, de taille $2 \times 3$.

Le constructeur `Constant` attend un tenseur PyTorch contenant les caractéristiques (*features*) de l'individu;le tenseur passé en argument **est** littéralement  $\mathcal{G}(c_i)$.


In [2]:
c1 = ltn.Constant(torch.tensor([2.1, 3]))
c2 = ltn.Constant(torch.tensor([[4.2, 3, 2.5], [4, -1.3, 1.8]]))

Une constante peut être définie comme apprenable via l'argument optionnel `trainable=True`. Ceci est utile pour apprendre des embeddings pour certains individus.

Rappel : une constante peut suivre deux régimes distincts.
- **prédéfinie (donnée)** : le tenseur est fixé une fois pour toutes à partir d'une donnée observée ; c'est le cas de $c_1$ et $c_2$ ci-dessus, qui ne changeront jamais.
- **apprenable (embedding)** : le tenseur devient un paramètre du modèle, ajusté par backpropagation, exactement comme les poids d'un réseau de neurones.

C'est utile lorsqu'on ne dispose d'aucune représentation numérique préexistante pour un individu : on initialise son tenseur (souvent aléatoirement), et on laisse le système apprendre lui-même la meilleure représentation, guidée uniquement par les contraintes logiques et les données du problème ; le principe même d'un embedding.

Les caractéristiques du tenseur seront alors considérées comme des paramètres entraînables (l'apprentissage en LTN sera expliqué dans un prochain notebook).

In [3]:
c3 = ltn.Constant(torch.tensor([0.,0.]), trainable=True)

Sous le capot, les constantes LTN sont implémentées via des objets `LTNObject`. Ces objets particuliers encapsulent une valeur (l'individu) ainsi qu'un attribut important appelé `free_vars`, qui sera expliqué plus loin dans ce tutoriel.

Si le paramètre `trainable` d'une constante LTN est fixé à `True`, alors le paramètre `requires_grad` du tenseur PyTorch contenu dans la constante sera lui aussi fixé à `True` ; c'est le mécanisme natif de PyTorch qui indique de calculer et stocker le gradient de ce tenseur lors de la backpropagation.

La valeur d'une constante LTN est accessible facilement via l'attribut `value`.

In [4]:
print(c1.value)
print(c3.value)
# here, we have to perform a detach before calling numpy(), because the tensor has requires_grad=True
print(c3.value.detach().numpy())

tensor([2.1000, 3.0000])
tensor([0., 0.], requires_grad=True)
[0. 0.]


## Prédicats

Les prédicats LTN sont des fonctions qui associent à un espace d'entrée $n$-aire une valeur dans $[0., 1.]$. En LTN, un prédicat peut être un réseau de neurones ou n'importe quelle autre fonction réalisant une telle correspondance.

Il existe différentes façons de construire un prédicat en LTN. Le constructeur `ltn.Predicate(model, func)` permet deux types de construction :
- si le paramètre `model` n'est pas `None`, le prédicat est construit à partir de l'instance de modèle `torch.nn.Module` fournie en entrée ;
- si le paramètre `model` est `None` et que le paramètre `func` n'est pas `None`, le prédicat est construit à partir de la fonction fournie en entrée. Cette construction par fonction est recommandée pour de petites opérations mathématiques **sans suivi de poids** (fonctions non entraînables).

Ci-dessous, on définit un prédicat $P_1$ via le paramètre `func`, et un prédicat $P_2$ via le paramètre `model`.

**Sur $P_1$** : la formule est $P_1(x) = \exp(-\|x-\mu\|)$, où $\|x-\mu\|$ est la distance euclidienne entre $x$ et le point fixe $\mu$.
Si $x=\mu$, la distance est nulle et $P_1(x)=\exp(0)=1$ (vérité maximale) ; plus $x$ s'éloigne de $\mu$, plus $P_1(x)$ tend vers $0$. C'est bien un prédicat valide, dont la sortie reste toujours dans $(0,1]$.

On peut remarquer l'accès à l'attribut `value` de la constante `mu` à l'intérieur de la définition du prédicat $P_1$. C'est nécessaire car `x` est un tenseur PyTorch brut, tandis que `mu` est une constante LTN (un `LTNObject`) ; **Règle générale** : chaque fois qu'un objet LTN (constante ou variable) intervient dans la définition d'un prédicat, il faut passer par son attribut `.value`.

**Sur $P_2$** : la dernière couche du réseau (`torch.nn.Linear(5,1)`) est suivie d'une **sigmoïde**. Ce n'est pas un détail cosmétique , c'est elle qui garantit structurellement que la sortie reste dans $[0,1]$, condition nécessaire pour qu'une fonction soit un prédicat valide au sens de Real Logic. Sans elle, la sortie pourrait prendre n'importe quelle valeur réelle.

In [5]:
mu = ltn.Constant(torch.tensor([2., 3.]))
P1 = ltn.Predicate(func=lambda x: torch.exp(-torch.norm(x - mu.value, dim=1)))

class ModelP2(torch.nn.Module):
    """For more info on how to use torch.nn.Module:
    https://pytorch.org/docs/stable/generated/torch.nn.Module.html"""
    def __init__(self):
        super(ModelP2, self).__init__()
        self.elu = torch.nn.ELU()
        self.sigmoid = torch.nn.Sigmoid()
        self.dense1 = torch.nn.Linear(2, 5)
        self.dense2 = torch.nn.Linear(5, 1) # returns one value in [0,1]

    def forward(self, x):
        x = self.elu(self.dense1(x))
        return self.sigmoid(self.dense2(x))

modelP2 = ModelP2()
P2 = ltn.Predicate(model=modelP2)

On peut interroger facilement les prédicats en utilisant des constantes et des variables LTN (voir plus loin dans ce notebook pour l'interrogation via des variables).

L'accès à l'attribut `value` sur le résultat de l'évaluation des prédicats est nécessaire ici car les prédicats LTN renvoient des instances de `LTNObject` — la valeur réelle du prédicat se trouve à l'intérieur de l'attribut `value` de cet objet retourné.

La dernière ligne, `print(P1(c1))` (sans `.value`), affichera l'objet `LTNObject` lui-même, avec sa structure interne — volontairement montré en contraste pour bien distinguer "la boîte" (`LTNObject`) de "son contenu" (`.value`).

In [6]:
c1 = ltn.Constant(torch.tensor([2.1, 3]))
c2 = ltn.Constant(torch.tensor([4.5, 0.8]))
c3 = ltn.Constant(torch.tensor([3.0, 4.8]))
print(P1(c1).value)
print(P1(c2).value)
print(P2(c3).value)
print(P1(c1))

tensor(0.9048)
tensor(0.0358)
tensor(0.6267, grad_fn=<ViewBackward0>)
LTNObject(value=tensor(0.9048), free_vars=[])


NOTES :
- Si un prédicat (ou une fonction) LTN prend plusieurs entrées, par exemple $P_4(x_1,x_2)$, les arguments doivent être séparés par une virgule.
- LTN convertit en interne les entrées de façon à toujours avoir une dimension "batch" sur le premier axe. Par conséquent, la plupart des opérations doivent utiliser `dim=1` (la dimension des caractéristiques/*features*).

Voici l'implémentation d'un prédicat binaire en LTN.

**Le mécanisme clé** : `torch.cat([x, y], dim=1)`. Un réseau de neurones classique ne prend qu'une seule entrée — la façon standard de lui faire accepter "deux arguments" est donc de **concaténer** les deux vecteurs en un seul, plus long, avant de le passer aux couches denses. Si $x$ et $y$ ont chacun 2 composantes, la concaténation donne un vecteur de 4 composantes — d'où `torch.nn.Linear(4, 5)` en première couche.

**Sur `dim=1`** : la dimension $0$ d'un tenseur LTN correspond toujours au batch (quel individu), et la dimension $1$ aux caractéristiques (quelles features à l'intérieur d'un individu). Concaténer avec `dim=1` fusionne donc les *features* de $x$ et $y$, sans jamais toucher à l'alignement du batch — même une constante seule est en interne traitée comme un "batch de taille 1".

In [7]:
class ModelP4(torch.nn.Module):
    def __init__(self):
        super(ModelP4, self).__init__()
        self.elu = torch.nn.ELU()
        self.sigmoid = torch.nn.Sigmoid()
        self.dense1 = torch.nn.Linear(4, 5)
        self.dense2 = torch.nn.Linear(5, 1) # returns one value in [0,1]

    def forward(self, x, y):
        x = torch.cat([x, y], dim=1)
        x = self.elu(self.dense1(x))
        return self.sigmoid(self.dense2(x))

P4 = ltn.Predicate(ModelP4())
c1 = ltn.Constant(torch.tensor([2.1, 3]))
c2 = ltn.Constant(torch.tensor([4.5, 0.8]))
print(P4(c1, c2).value) # multiple arguments are separated by a comma

tensor(0.4338, grad_fn=<ViewBackward0>)


Pour plus de détails et d'autres façons utiles de créer des prédicats (y compris comment intégrer des classifieurs multiclasses en tant que prédicats binaires), voir les exemples inclus dans le dossier `/examples` de ce dépôt.

## Fonctions

Les fonctions LTN sont groundées comme n'importe quelle fonction mathématique associant $n$ individus à un individu unique dans le domaine des tenseurs.

Il existe différentes façons de construire une fonction en LTN. Le constructeur `ltn.Function(model, func)` permet deux types de construction :
- si le paramètre `model` n'est pas `None`, la fonction est construite à partir de l'instance de modèle `torch.nn.Module` fournie en entrée ;
- si le paramètre `model` est `None` et que le paramètre `func` n'est pas `None`, la fonction est construite à partir de la fonction fournie en entrée. Cette construction par fonction est recommandée pour de petites opérations mathématiques **sans suivi de poids** (fonction non entraînable).

Ci-dessous, on définit une fonction $f_1$ via le paramètre `func`, et une fonction $f_2$ via le paramètre `model`.

**Différence essentielle avec un prédicat** : ici, $f_1(x,y) = x - y$ ne comporte **ni sigmoïde ni aucune contrainte de sortie** ; une fonction peut renvoyer n'importe quel tenseur, de n'importe quelle valeur. C'est cohérent avec la théorie : une fonction reste "dans" l'espace des tenseurs (elle renvoie un individu du domaine), elle ne produit pas un jugement de vérité. Et c'est aussi pourquoi la dernière couche de $f_2$ (`dense2`) n'est suivie d'aucune activation de type sigmoïde.

**Signal visuel à retenir** : la présence ou l'absence d'une sigmoïde en dernière couche permet de reconnaître immédiatement, dans n'importe quel notebook LTN, si un `torch.nn.Module` définit un prédicat ou une fonction.

In [8]:
f1 = ltn.Function(func=lambda x, y: x - y)

class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = torch.nn.Linear(2, 10)
        self.dense2 = torch.nn.Linear(10, 5)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        x = self.relu(self.dense1(x))
        return self.dense2(x)

model_f2 = MyModel()
f2 = ltn.Function(model=model_f2)

On peut facilement calculer des fonctions en utilisant des constantes et des variables LTN comme entrées (voir plus loin dans ce notebook pour l'utilisation avec des variables).

La sortie d'une fonction LTN est également un `LTNObject`, comme on l'a déjà vu pour les prédicats.

La même remarque concernant la nécessité d'accéder au paramètre `value` de l'`LTNObject` retourné reste valable pour les fonctions LTN.

In [9]:
c1 = ltn.Constant(torch.tensor([2.1, 3]))
c2 = ltn.Constant(torch.tensor([4.5, 0.8]))
print(f1(c1, c2).value) # multiple arguments are separated by a comma
print(f2(c1).value)
print(f2(c1))

tensor([-2.4000,  2.2000])
tensor([ 0.2885,  0.5843,  0.8049, -0.6174,  1.1797], grad_fn=<ViewBackward0>)
LTNObject(value=tensor([ 0.2885,  0.5843,  0.8049, -0.6174,  1.1797], grad_fn=<ViewBackward0>), free_vars=[])


## Variables

Jusqu'ici, une constante représentait toujours un seul individu fixe. Une **variable** LTN va plus loin : elle représente un batch de plusieurs individus, une séquence et non un ensemble, ce qui signifie que le même individu peut très bien apparaître deux fois, contrairement à un ensemble mathématique classique où les doublons n'existent pas.

C'est cette notion de variable qui permet d'écrire des affirmations quantifiées comme $\forall x\ P(x)$, puisque « pour tout $x$ » n'a de sens que si $x$ peut effectivement parcourir plusieurs individus.

Le point technique à retenir est que chaque variable doit obligatoirement porter un label, une chaîne de caractères (`'x'`, `'y'`, etc.) qu'on lui donne à la création. Ce label n'est pas cosmétique : LTN s'en sert en interne pour savoir, lors de calculs impliquant plusieurs variables, quelle dimension d'un résultat appartient à quelle variable, comme on le verra concrètement juste après.

Comme toute entité LTN, une variable est enveloppée dans un `LTNObject`, dont l'attribut `.value` contient le tenseur batch lui-même, et dont l'attribut `.free_vars` contient la liste des labels des variables libres qu'elle renferme.

Une variable est dite libre tant qu'elle n'a pas été capturée par un quantificateur ($\forall$ ou $\exists$) — les quantificateurs seront introduits dans le notebook suivant. Pour l'instant, une variable seule est toujours libre par rapport à elle-même, donc `free_vars` d'une variable `x` vaut simplement `['x']`. C'est aussi ce qui explique pourquoi `free_vars` d'une constante est une liste vide : une constante ne varie jamais, elle n'a donc rien à libérer.

In [10]:
x = ltn.Variable('x', torch.randn((10, 2)))
y = ltn.Variable('y', torch.randn((5, 2)))

Que se passe-t-il quand on évalue un prédicat sur une variable plutôt que sur une constante ?

Avec une seule variable, la réponse est directe : si $x$ contient $n$ individus, $P(x)$ produit $n$ résultats, un par individu, exactement comme un batch classique en deep learning.

Avec deux variables, le comportement est moins évident et mérite d'être bien compris. LTN ne fait pas correspondre le premier individu de $x$ avec le premier individu de $y$, le second avec le second, et ainsi de suite. Il évalue au contraire toutes les combinaisons possibles, un peu comme une table de multiplication à double entrée où chaque case est le résultat pour une paire ligne-colonne.

Concrètement, si $x$ a $n_x$ individus et $y$ a $n_y$ individus, $P(x,y)$ produit $n_x \times n_y$ résultats, organisés en une matrice de forme $(n_x, n_y)$ où la case $(i,j)$ contient exactement $P(x_i, y_j)$.

C'est précisément ce qu'illustre l'exemple ci-dessous : $x$ a 10 individus, $y$ en a 5, donc $P_4(x,y)$ produit une matrice de forme $(10,5)$, soit 50 évaluations, une par paire possible. L'attribut `free_vars` du résultat contient alors `['x', 'y']`, ce qui indique précisément que l'axe 0 correspond à $x$ et l'axe 1 à $y$. C'est cette information qui permet d'indexer directement le résultat, par exemple `res1.value[2, 0]` pour récupérer l'évaluation entre le 3e individu de $x$ et le 1er de $y$.

`shape()` est simplement un raccourci pratique pour `res1.value.shape`.

In [11]:
# Notice that the outcome is a 2-dimensional tensor where each cell
# represents the satisfiability of P4 evaluated with each individual in x and in y.
P4 = ltn.Predicate(ModelP4())
res1 = P4(x, y)
print(res1.shape())
print(res1.free_vars) # dynamically added attribute; tells that axis 0 corresponds to x and axis 1 to y
print(res1.value[2, 0]) # gives the result computed with the 3rd individual in x and the 1st individual in y
print(res1.value)

torch.Size([10, 5])
['x', 'y']
tensor(0.4597, grad_fn=<SelectBackward0>)
tensor([[0.4123, 0.4681, 0.3839, 0.3185, 0.2287],
        [0.4042, 0.4494, 0.3715, 0.3273, 0.2354],
        [0.4597, 0.4880, 0.4254, 0.4086, 0.3080],
        [0.3982, 0.4541, 0.3704, 0.3040, 0.2186],
        [0.3614, 0.4152, 0.3405, 0.2670, 0.1971],
        [0.3598, 0.4134, 0.3394, 0.2654, 0.1964],
        [0.4314, 0.4773, 0.3979, 0.3487, 0.2536],
        [0.4165, 0.4724, 0.3881, 0.3226, 0.2318],
        [0.3488, 0.4017, 0.3307, 0.2552, 0.1909],
        [0.4301, 0.4840, 0.4008, 0.3352, 0.2425]], grad_fn=<ViewBackward0>)


Le même principe s'applique à une fonction, avec une nuance : puisqu'une fonction ne renvoie pas un scalaire dans $[0,1]$ mais un vecteur quelconque, un axe supplémentaire vient s'ajouter à la fin du résultat.

Ici, si la fonction renvoie un vecteur de $\mathbb{R}^2$, le résultat sur $x$ (10 individus) et $y$ (5 individus) aura la forme $(10, 5, 2)$. Les deux premiers axes indexent toujours la paire d'individus concernée, comme pour un prédicat, tandis que le troisième axe correspond aux deux composantes du vecteur renvoyé pour cette paire.

In [12]:
# Notice that the last axe(s) correspond to the dimensions of the outcome;
# here, f1 projects to outcomes in R^2, so the outcome has one additional axis of dimension 2.
# the output tensor has shape (10, 5, 2) because variable x has 10 individuals, y has 5 individuals, and f1 maps in R^2
res2 = f1(x, y)
print(res2.shape())
print(res2.free_vars)
print(res2.value[2,0]) # gives the result calculated with the 3rd individual in x and the 1st individual in y
print(res2.value)

torch.Size([10, 5, 2])
['x', 'y']
tensor([-2.4795,  0.8113])
tensor([[[ 0.2054, -0.1212],
         [-0.0711, -0.6304],
         [ 0.6780, -0.6543],
         [ 0.4287,  1.4174],
         [ 1.6607,  0.7982]],

        [[ 0.3505,  2.7907],
         [ 0.0740,  2.2815],
         [ 0.8232,  2.2576],
         [ 0.5738,  4.3293],
         [ 1.8058,  3.7101]],

        [[-2.4795,  0.8113],
         [-2.7560,  0.3021],
         [-2.0068,  0.2782],
         [-2.2562,  2.3499],
         [-1.0242,  1.7306]],

        [[ 0.7321,  0.8978],
         [ 0.4556,  0.3886],
         [ 1.2048,  0.3647],
         [ 0.9554,  2.4364],
         [ 2.1874,  1.8171]],

        [[ 1.4323,  0.0301],
         [ 1.1558, -0.4791],
         [ 1.9049, -0.5031],
         [ 1.6555,  1.5686],
         [ 2.8875,  0.9494]],

        [[ 1.3249, -0.8637],
         [ 1.0484, -1.3729],
         [ 1.7976, -1.3968],
         [ 1.5482,  0.6749],
         [ 2.7802,  0.0556]],

        [[-0.3948,  1.6215],
         [-0.6713,  1.1123],

Un dernier cas mérite d'être vu : que se passe-t-il si on mélange une variable et une constante dans un même appel ?

La réponse découle directement de ce qu'on vient d'établir. Une constante représente un seul individu fixe, elle n'a donc rien à faire varier de son côté, si bien que le produit cartésien ne porte que sur la variable restante.

Concrètement, $P_4(c_1, y)$ avec $y$ contenant 5 individus donne un simple vecteur de 5 valeurs, et non une matrice, puisque $c_1$ ne contribue à aucun axe. La case $i$ contient l'évaluation du prédicat entre $c_1$ et le $i$-ème individu de $y$. Logiquement, `free_vars` du résultat ne contient plus que `['y']`, puisque $c_1$ n'a jamais été une variable et ne pouvait donc pas figurer dans cette liste.

In [13]:
c1 = ltn.Constant(torch.tensor([2.1, 3]))
res3 = P4(c1, y)
print(res3.shape()) # Notice that no axis is associated to a constant. The output has shape (5,) because variable y has
# 5 individuals
print(res3.free_vars)
print(res3.value[0]) # gives the result calculated with c1 and the 1st individual in y
print(res3.value)

torch.Size([5])
['y']
tensor(0.3388, grad_fn=<SelectBackward0>)
tensor([0.3388, 0.3908, 0.3224, 0.2462, 0.1857], grad_fn=<ViewBackward0>)


### Variables construites à partir de constantes entraînables

En LTN, il est possible de construire une variable dont les individus sont eux-mêmes des constantes entraînables. C'est particulièrement utile pour l'apprentissage d'embeddings, lorsque chaque individu d'une variable doit voir sa représentation numérique apprise plutôt que fixée à l'avance.

Pour bien saisir l'intérêt de ce mécanisme, il est conseillé de consulter l'exemple `Smokes-friends-cancer`, qui illustre concrètement l'usage de variables composées de constantes entraînables.

Dans l'exemple ci-dessous, deux constantes entraînables sont d'abord déclarées, puis une variable LTN est construite à partir d'elles via `torch.stack` : le premier individu de la variable correspond à la première constante, le second à la seconde.

Après évaluation de $P_2$ sur $x$, le gradient peut bien remonter jusqu'aux valeurs numériques de $c_1$ et $c_2$ lors d'une backpropagation, puisque `torch.stack` est une opération différentiable qui les relie à $x$. C'est ce mécanisme qui permettra, lors de l'entraînement, d'ajuster progressivement ces deux constantes pour mieux satisfaire les contraintes logiques du modèle.

Un détail technique mérite cependant d'être clarifié pour éviter toute confusion : après application du prédicat, `c1.value.grad_fn` et `c2.value.grad_fn` restent à `None`. Cela ne signifie pas que $c_1$ et $c_2$ demeurent inchangées par l'entraînement, bien au contraire, leurs valeurs numériques seront bel et bien mises à jour si elles sont enregistrées comme paramètres d'un optimiseur. Ce que cet attribut indique en réalité, c'est simplement que `c1.value` et `c2.value` sont des tenseurs *feuilles* : ils ont été créés directement, et non comme le résultat d'une opération PyTorch, ce qui est une propriété structurelle valable pour toute feuille, indépendamment de son utilisation ultérieure dans `torch.stack`. Le gradient calculé lors d'une backpropagation ira bien les alimenter via leur attribut `.grad`, ce qui permettra à un optimiseur de les mettre à jour normalement.

C'est aussi pour cette raison technique qu'on fournit à la variable les valeurs des constantes (`c1.value`, `c2.value`) plutôt que les objets `Constant` eux-mêmes : une variable LTN n'accepte que des tenseurs PyTorch bruts en entrée.

In [14]:
c1 = ltn.Constant(torch.tensor([2.1, 3]), trainable=True)
c2 = ltn.Constant(torch.tensor([4.5, 0.8]), trainable=True)

# PyTorch will keep track of the gradients between c1, c2 and x.
# Read tutorial 3 for more details.
x = ltn.Variable('x', torch.stack([c1.value, c2.value]))
res = P2(x)
print(res.value)

print(x.value[0])
print(x.value[1])

print(c1.value.grad_fn)
print(c2.value.grad_fn)

tensor([0.6416, 0.5111], grad_fn=<ViewBackward0>)
tensor([2.1000, 3.0000], grad_fn=<SelectBackward0>)
tensor([4.5000, 0.8000], grad_fn=<SelectBackward0>)
None
None
